//! USING and NATURAL joins across raw, dynamic, and typed.
const std = @import("std");
const sqlite = @import("sqlite");

const Left = sqlite.table("un_left", struct { id: i64, grp: []const u8, val: []const u8 });
const Right = sqlite.table("un_right", struct { id: i64, grp: []const u8, info: []const u8 });

pub fn main() !void {
    var db = try sqlite.open(std.heap.page_allocator, "example_59.db");
    const t_db_un_left = db.table("un_left");
    errdefer db.close();
    var setup = try db.exec("DROP TABLE IF EXISTS un_left; DROP TABLE IF EXISTS un_right; CREATE TABLE un_left (id INTEGER NOT NULL, grp TEXT NOT NULL, val TEXT NOT NULL); CREATE TABLE un_right (id INTEGER NOT NULL, grp TEXT NOT NULL, info TEXT NOT NULL); INSERT INTO un_left VALUES (1, 'g1', 'L1'), (2, 'g2', 'L2'), (3, 'g1', 'L3'); INSERT INTO un_right VALUES (2, 'g2', 'R2'), (3, 'g9', 'R3'), (4, 'g4', 'R4');");
    setup.deinit();
    try db.schema(Left).validate();
    try db.schema(Right).validate();
    var rawUsing = try db.exec("SELECT id, un_left.grp, val, info FROM un_left JOIN un_right USING (id) ORDER BY id;");
    defer rawUsing.deinit();
    if (rawUsing.count() != 2) return error.VerificationFailed;
    if (rawUsing.at(0)[0].integer != 2) return error.VerificationFailed;
    var dynUsing = try t_db_un_left.joinUsing("un_right", t_db_un_left.column("id")).orderBy(t_db_un_left.column("id").asc()).fetch();
    defer dynUsing.deinit();
    if (dynUsing.count() != rawUsing.count()) return error.VerificationFailed;
    if (dynUsing.columns.len != 5) return error.VerificationFailed;
    if (dynUsing.at(0)[0].integer != 2) return error.VerificationFailed;
    if (!std.mem.eql(u8, dynUsing.at(0)[2].text, "L2")) return error.VerificationFailed;
    if (!std.mem.eql(u8, dynUsing.at(0)[4].text, "R2")) return error.VerificationFailed;
    var typedUsing = try db.from(Left).joinUsing(Right, Left.id).orderBy(Left.id.asc()).fetch();
    defer typedUsing.deinit();
    if (typedUsing.count() != 2) return error.VerificationFailed;
    if (typedUsing.at(0).id != 2) return error.VerificationFailed;
    var rawNatural = try db.exec("SELECT id, grp, val, info FROM un_left NATURAL JOIN un_right;");
    defer rawNatural.deinit();
    if (rawNatural.count() != 1) return error.VerificationFailed;
    var dynNatural = try t_db_un_left.naturalJoin("un_right").fetch();
    defer dynNatural.deinit();
    if (dynNatural.count() != 1) return error.VerificationFailed;
    if (dynNatural.columns.len != 4) return error.VerificationFailed;
    if (!std.mem.eql(u8, dynNatural.at(0)[3].text, "R2")) return error.VerificationFailed;
    var typedNatural = try db.from(Left).naturalJoin(Right).fetch();
    defer typedNatural.deinit();
    if (typedNatural.count() != 1) return error.VerificationFailed;
    if (typedNatural.at(0).id != 2) return error.VerificationFailed;
    var dynLeft = try t_db_un_left.leftJoinUsing("un_right", t_db_un_left.column("id")).orderBy(t_db_un_left.column("id").asc()).fetch();
    defer dynLeft.deinit();
    if (dynLeft.count() != 3) return error.VerificationFailed;
    var rawLeft = try db.exec("SELECT id, un_left.grp, val, info FROM un_left LEFT JOIN un_right USING (id) ORDER BY id;");
    defer rawLeft.deinit();
    if (rawLeft.count() != dynLeft.count()) return error.VerificationFailed;
    var typedLeft = try db.from(Left).naturalLeftJoin(Right).orderBy(Left.id.asc()).fetch();
    defer typedLeft.deinit();
    if (typedLeft.count() != 3) return error.VerificationFailed;
    var inserted = try db.from(Left).insert(.{ .id = 5, .grp = "g5", .val = "L5" });
    inserted.deinit();
    var afterInsert = try db.exec("SELECT count(*) FROM un_left;");
    defer afterInsert.deinit();
    if (afterInsert.at(0)[0].integer != 4) return error.VerificationFailed;
    var dynAfter = try t_db_un_left.naturalLeftJoin("un_right").fetch();
    defer dynAfter.deinit();
    if (dynAfter.count() != 4) return error.VerificationFailed;
    db.close();
    var reopened = try sqlite.open(std.heap.page_allocator, "example_59.db");
    const t_reopened_un_left = reopened.table("un_left");
    defer reopened.close();
    var persisted = try reopened.exec("SELECT * FROM un_left JOIN un_right USING (id) ORDER BY id;");
    defer persisted.deinit();
    if (persisted.count() != 2) return error.VerificationFailed;
    if (persisted.columns.len != 5) return error.VerificationFailed;
    var persistedDyn = try t_reopened_un_left.naturalJoin("un_right").fetch();
    defer persistedDyn.deinit();
    if (persistedDyn.count() != 1) return error.VerificationFailed;
    std.debug.print("59 using natural joins: raw dynamic typed verified with persistence\n", .{});
}
