const std = @import("std");
const sqlite = @import("sqlite");

const Left = sqlite.table("cp_left", struct { id: ?i64, label: ?[]const u8 });
const Right = sqlite.table("cp_right", struct { id: ?i64, label: ?[]const u8 });

pub fn main() !void {
    var db = try sqlite.open(std.heap.page_allocator, "example_61.db");
    const t_db_cp_left = db.table("cp_left");
    const t_db_cp_right = db.table("cp_right");
    errdefer db.close();
    var setup = try db.exec("DROP TABLE IF EXISTS cp_left; DROP TABLE IF EXISTS cp_right; CREATE TABLE cp_left (id INTEGER, label TEXT); CREATE TABLE cp_right (id INTEGER, label TEXT); INSERT INTO cp_left VALUES (1, 'alpha'), (2, 'beta'), (2, 'beta'), (NULL, 'null'), (4, 'delta'); INSERT INTO cp_right VALUES (2, 'beta'), (3, 'gamma'), (NULL, 'null'), (5, 'eps');");
    setup.deinit();
    try db.schema(Left).validate();
    try db.schema(Right).validate();
    var rawUnion = try db.exec("SELECT id FROM cp_left UNION SELECT id FROM cp_right ORDER BY id;");
    defer rawUnion.deinit();
    if (rawUnion.count() != 6) return error.VerificationFailed;
    if (rawUnion.at(0)[0] != .null) return error.VerificationFailed;
    if (rawUnion.at(5)[0].integer != 5) return error.VerificationFailed;
    var dynUnion = try t_db_cp_left.select(.{t_db_cp_left.column("id")}).unionDistinct(t_db_cp_right.select(.{t_db_cp_right.column("id")})).orderBy(t_db_cp_left.column("id").asc()).fetch();
    defer dynUnion.deinit();
    if (dynUnion.count() != rawUnion.count()) return error.VerificationFailed;
    for (rawUnion.rows, 0..) |row, i| {
        if (row[0] == .null) {
            if (dynUnion.at(i)[0] != .null) return error.VerificationFailed;
        } else if (dynUnion.at(i)[0].integer != row[0].integer) return error.VerificationFailed;
    }
    var rawAll = try db.exec("SELECT id FROM cp_left UNION ALL SELECT id FROM cp_right;");
    defer rawAll.deinit();
    if (rawAll.count() != 9) return error.VerificationFailed;
    var dynAll = try t_db_cp_left.select(.{t_db_cp_left.column("id")}).unionAll(t_db_cp_right.select(.{t_db_cp_right.column("id")})).fetch();
    defer dynAll.deinit();
    if (dynAll.count() != 9) return error.VerificationFailed;
    var rawIntersect = try db.exec("SELECT id FROM cp_left INTERSECT SELECT id FROM cp_right;");
    defer rawIntersect.deinit();
    if (rawIntersect.count() != 2) return error.VerificationFailed;
    var dynIntersect = try t_db_cp_left.select(.{t_db_cp_left.column("id")}).intersect(t_db_cp_right.select(.{t_db_cp_right.column("id")})).fetch();
    defer dynIntersect.deinit();
    if (dynIntersect.count() != 2) return error.VerificationFailed;
    if (dynIntersect.at(0)[0].integer != 2) return error.VerificationFailed;
    if (dynIntersect.at(1)[0] != .null) return error.VerificationFailed;
    var rawExcept = try db.exec("SELECT id FROM cp_left EXCEPT SELECT id FROM cp_right;");
    defer rawExcept.deinit();
    if (rawExcept.count() != 2) return error.VerificationFailed;
    var dynExcept = try t_db_cp_left.select(.{t_db_cp_left.column("id")}).except(t_db_cp_right.select(.{t_db_cp_right.column("id")})).fetch();
    defer dynExcept.deinit();
    if (dynExcept.count() != 2) return error.VerificationFailed;
    if (dynExcept.at(0)[0].integer != 1) return error.VerificationFailed;
    if (dynExcept.at(1)[0].integer != 4) return error.VerificationFailed;
    var crossType = try db.exec("SELECT 1 UNION SELECT 1.0;");
    defer crossType.deinit();
    if (crossType.count() != 1) return error.VerificationFailed;
    var rawPaged = try db.exec("SELECT id FROM cp_left UNION SELECT id FROM cp_right ORDER BY id LIMIT 2 OFFSET 1;");
    defer rawPaged.deinit();
    if (rawPaged.count() != 2) return error.VerificationFailed;
    if (rawPaged.at(0)[0].integer != 1) return error.VerificationFailed;
    var dynPaged = try t_db_cp_left.select(.{t_db_cp_left.column("id")}).unionDistinct(t_db_cp_right.select(.{t_db_cp_right.column("id")})).orderBy(t_db_cp_left.column("id").asc()).limit(2).offset(1).fetch();
    defer dynPaged.deinit();
    if (dynPaged.count() != 2) return error.VerificationFailed;
    if (dynPaged.at(0)[0].integer != 1) return error.VerificationFailed;
    var rawChain = try db.exec("SELECT id FROM cp_left EXCEPT SELECT id FROM cp_right UNION SELECT id FROM cp_right ORDER BY id;");
    defer rawChain.deinit();
    if (rawChain.count() != 6) return error.VerificationFailed;
    var dynChain = try t_db_cp_left.select(.{t_db_cp_left.column("id")}).except(t_db_cp_right.select(.{t_db_cp_right.column("id")})).unionDistinct(t_db_cp_right.select(.{t_db_cp_right.column("id")})).orderBy(t_db_cp_left.column("id").asc()).fetch();
    defer dynChain.deinit();
    if (dynChain.count() != 6) return error.VerificationFailed;
    var typedUnion = try db.from(Left).unionDistinct(db.from(Right)).fetch();
    defer typedUnion.deinit();
    if (typedUnion.count() != 6) return error.VerificationFailed;
    if (typedUnion.at(0).id.? != 1) return error.VerificationFailed;
    var typedIds = try db.from(Left).select(.{Left.id}).unionDistinct(db.from(Right).select(.{Right.id})).orderBy(Left.id.asc()).fetch();
    defer typedIds.deinit();
    if (typedIds.count() != 6) return error.VerificationFailed;
    if (typedIds.at(0)[0] != .null) return error.VerificationFailed;
    var one = try db.from(Left).where(Left.id.eq(1)).unionDistinct(db.from(Right).where(Right.id.gt(100))).fetchOne();
    if (one.id.? != 1) return error.VerificationFailed;
    db.from(Left).freeRow(&one);
    var inserted = try db.from(Left).insert(.{ .id = 6, .label = "zeta" });
    inserted.deinit();
    var afterInsert = try db.exec("SELECT id FROM cp_left UNION SELECT id FROM cp_right ORDER BY id;");
    defer afterInsert.deinit();
    if (afterInsert.count() != 7) return error.VerificationFailed;
    var dynAfter = try t_db_cp_left.select(.{t_db_cp_left.column("id")}).unionDistinct(t_db_cp_right.select(.{t_db_cp_right.column("id")})).orderBy(t_db_cp_left.column("id").asc()).fetch();
    defer dynAfter.deinit();
    if (dynAfter.count() != 7) return error.VerificationFailed;
    if (db.exec("SELECT id FROM cp_left UNION SELECT id, label FROM cp_right;")) |r| {
        var owned = r;
        owned.deinit();
        return error.VerificationFailed;
    } else |_| {}
    var intactLeft = try db.exec("SELECT count(*) FROM cp_left;");
    defer intactLeft.deinit();
    if (intactLeft.at(0)[0].integer != 6) return error.VerificationFailed;
    var intactRight = try db.exec("SELECT count(*) FROM cp_right;");
    defer intactRight.deinit();
    if (intactRight.at(0)[0].integer != 4) return error.VerificationFailed;
    db.close();
    var reopened = try sqlite.open(std.heap.page_allocator, "example_61.db");
    const t_reopened_cp_left = reopened.table("cp_left");
    const t_reopened_cp_right = reopened.table("cp_right");
    defer reopened.close();
    var persisted = try reopened.exec("SELECT id FROM cp_left UNION SELECT id FROM cp_right ORDER BY id;");
    defer persisted.deinit();
    if (persisted.count() != 7) return error.VerificationFailed;
    var persistedDyn = try t_reopened_cp_left.select(.{t_reopened_cp_left.column("id")}).unionDistinct(t_reopened_cp_right.select(.{t_reopened_cp_right.column("id")})).orderBy(t_reopened_cp_left.column("id").asc()).fetch();
    defer persistedDyn.deinit();
    if (persistedDyn.count() != 7) return error.VerificationFailed;
    std.debug.print("61 compound dsl: raw dynamic typed verified with persistence\n", .{});
}
