const std = @import("std");
const sqlite = @import("sqlite");

const Parent = sqlite.table("pg_parent", struct { id: i64, label: []const u8 });
const Child = sqlite.table("pg_child", struct { id: i64, parent_id: ?i64, label: []const u8 });

pub fn main() !void {
    var db = try sqlite.open(std.heap.page_allocator, "example_62.db");
    const t_db_pg_child = db.table("pg_child");
    errdefer db.close();
    var setup = try db.exec("DROP TABLE IF EXISTS pg_child; DROP TABLE IF EXISTS pg_parent; CREATE TABLE pg_parent (id INTEGER NOT NULL PRIMARY KEY, label TEXT NOT NULL); CREATE TABLE pg_child (id INTEGER NOT NULL PRIMARY KEY, parent_id INTEGER REFERENCES pg_parent(id), label TEXT NOT NULL); INSERT INTO pg_parent VALUES (1, 'one'), (2, 'two');");
    setup.deinit();
    try db.schema(Parent).validate();
    try db.schema(Child).validate();
    var inserted = try db.from(Child).insert(.{ .id = 10, .parent_id = 1, .label = "ok" });
    inserted.deinit();
    var cleanCheck = try db.exec("PRAGMA foreign_key_check;");
    defer cleanCheck.deinit();
    if (cleanCheck.count() != 0) return error.VerificationFailed;
    var cleanIntegrity = try db.exec("PRAGMA integrity_check;");
    defer cleanIntegrity.deinit();
    if (cleanIntegrity.count() != 1) return error.VerificationFailed;
    if (!std.mem.eql(u8, cleanIntegrity.at(0)[0].text, "ok")) return error.VerificationFailed;
    var foreignOff = try db.exec("PRAGMA foreign_keys = OFF;");
    defer foreignOff.deinit();
    var orphan = try db.from(Child).insert(.{ .id = 11, .parent_id = 99, .label = "orphan" });
    orphan.deinit();
    var foreignOn = try db.exec("PRAGMA foreign_keys = ON;");
    defer foreignOn.deinit();
    var violations = try db.exec("PRAGMA foreign_key_check;");
    defer violations.deinit();
    if (violations.count() != 1) return error.VerificationFailed;
    if (!std.mem.eql(u8, violations.at(0)[0].text, "pg_child")) return error.VerificationFailed;
    if (violations.at(0)[1].integer != 2) return error.VerificationFailed;
    if (!std.mem.eql(u8, violations.at(0)[2].text, "pg_parent")) return error.VerificationFailed;
    if (violations.at(0)[3].integer != 0) return error.VerificationFailed;
    var scoped = try db.exec("PRAGMA foreign_key_check(pg_child);");
    defer scoped.deinit();
    if (scoped.count() != 1) return error.VerificationFailed;
    var stillClean = try db.exec("PRAGMA integrity_check;");
    defer stillClean.deinit();
    if (stillClean.count() != 1) return error.VerificationFailed;
    if (!std.mem.eql(u8, stillClean.at(0)[0].text, "ok")) return error.VerificationFailed;
    var deleted = try db.exec("DELETE FROM pg_child WHERE id = 11;");
    deleted.deinit();
    var healed = try db.exec("PRAGMA foreign_key_check;");
    defer healed.deinit();
    if (healed.count() != 0) return error.VerificationFailed;
    var dynHealed = try t_db_pg_child.selectAll().fetch();
    defer dynHealed.deinit();
    if (dynHealed.count() != 1) return error.VerificationFailed;
    var cacheDefault = try db.exec("PRAGMA cache_size;");
    defer cacheDefault.deinit();
    if (cacheDefault.at(0)[0].integer != -2000) return error.VerificationFailed;
    var cacheSet = try db.exec("PRAGMA cache_size = 500;");
    defer cacheSet.deinit();
    if (cacheSet.at(0)[0].integer != 500) return error.VerificationFailed;
    var syncDefault = try db.exec("PRAGMA synchronous;");
    defer syncDefault.deinit();
    if (syncDefault.at(0)[0].integer != 2) return error.VerificationFailed;
    var syncSet = try db.exec("PRAGMA synchronous = NORMAL;");
    defer syncSet.deinit();
    if (syncSet.at(0)[0].integer != 1) return error.VerificationFailed;
    db.close();
    var reopened = try sqlite.open(std.heap.page_allocator, "example_62.db");
    defer reopened.close();
    var persistedRows = try reopened.exec("SELECT count(*) FROM pg_child;");
    defer persistedRows.deinit();
    if (persistedRows.at(0)[0].integer != 1) return error.VerificationFailed;
    var persistedCheck = try reopened.exec("PRAGMA foreign_key_check;");
    defer persistedCheck.deinit();
    if (persistedCheck.count() != 0) return error.VerificationFailed;
    var persistedIntegrity = try reopened.exec("PRAGMA integrity_check;");
    defer persistedIntegrity.deinit();
    if (!std.mem.eql(u8, persistedIntegrity.at(0)[0].text, "ok")) return error.VerificationFailed;
    var resetCache = try reopened.exec("PRAGMA cache_size;");
    defer resetCache.deinit();
    if (resetCache.at(0)[0].integer != -2000) return error.VerificationFailed;
    var resetSync = try reopened.exec("PRAGMA synchronous;");
    defer resetSync.deinit();
    if (resetSync.at(0)[0].integer != 2) return error.VerificationFailed;
    std.debug.print("62 pragma checks: foreign_key_check, integrity_check, and settings verified with persistence\n", .{});
}
