const std = @import("std");
const connection = @import("connection/connection.zig");

pub const Connection = connection.Connection;
pub const open = Connection.open;
pub const Result = @import("connection/result.zig").Result;
pub const Statement = @import("connection/statement.zig").Statement;
pub const Value = @import("vm/value.zig").Value;
pub const errors = @import("errors/errors.zig");
pub const table = @import("dsl/table.zig").table;
pub const tableWith = @import("dsl/table.zig").tableWith;
pub const aliased = @import("dsl/table.zig").aliased;
pub const DynamicTable = @import("dsl/dynamic.zig").DynamicTable;
pub const DynamicColumn = @import("dsl/column.zig").DynamicColumn;
pub const SchemaHandle = @import("dsl/dynamic.zig").SchemaHandle;
pub const column = @import("dsl/column.zig").column;
pub const caseWhen = @import("dsl/column.zig").caseWhen;
pub const caseValue = @import("dsl/column.zig").caseValue;
pub const rowNumber = @import("dsl/column.zig").rowNumber;
pub const rank = @import("dsl/column.zig").rank;
pub const denseRank = @import("dsl/column.zig").denseRank;
pub const percentRank = @import("dsl/column.zig").percentRank;
pub const cumeDist = @import("dsl/column.zig").cumeDist;
pub const ntile = @import("dsl/column.zig").ntile;
pub const lag = @import("dsl/column.zig").lag;
pub const lead = @import("dsl/column.zig").lead;
pub const firstValue = @import("dsl/column.zig").firstValue;
pub const lastValue = @import("dsl/column.zig").lastValue;
pub const nthValue = @import("dsl/column.zig").nthValue;
pub const unboundedPreceding = @import("dsl/column.zig").unboundedPreceding;
pub const preceding = @import("dsl/column.zig").preceding;
pub const currentRow = @import("dsl/column.zig").currentRow;
pub const following = @import("dsl/column.zig").following;
pub const unboundedFollowing = @import("dsl/column.zig").unboundedFollowing;
pub const migration = struct {
    pub const Migration = @import("migration/migration.zig").Migration;
    pub const Set = @import("migration/migration.zig").Set;
    pub const Runner = @import("migration/runner.zig").Runner;
};
pub const version = @import("version.zig");

test {
    _ = @import("format/varint.zig");
    _ = @import("format/header.zig");
    _ = @import("format/record.zig");
    _ = @import("format/page.zig");
    _ = @import("vm/value.zig");
    _ = @import("vm/vm.zig");
    _ = @import("vm/compiler.zig");
    _ = @import("vm/opcode.zig");
    _ = @import("storage/file.zig");
    _ = @import("storage/pager.zig");
    _ = @import("storage/wal.zig");
    _ = @import("storage/journal.zig");
    _ = @import("storage/image.zig");
    _ = @import("storage/sqlite_image.zig");
    _ = @import("errors/errors.zig");
    _ = @import("sql/token.zig");
    _ = @import("sql/lexer.zig");
    _ = @import("sql/ast.zig");
    _ = @import("sql/parser.zig");
    _ = @import("sql/expr.zig");
    _ = @import("connection/connection.zig");
    _ = @import("connection/result.zig");
    _ = @import("connection/statement.zig");
    _ = @import("dsl/expr.zig");
    _ = @import("dsl/column.zig");
    _ = @import("dsl/keys.zig");
    _ = @import("dsl/table.zig");
    _ = @import("dsl/query_builder.zig");
    _ = @import("dsl/ast_builder.zig");
    _ = @import("dsl/dynamic.zig");
    _ = @import("migration/migration.zig");
    _ = @import("migration/runner.zig");
    _ = @import("catalog/schema.zig");
    _ = @import("catalog/type_affinity.zig");
    _ = @import("catalog/table_def.zig");
    _ = @import("catalog/index_def.zig");
    _ = @import("btree/btree.zig");
    _ = @import("btree/cursor.zig");
    _ = @import("btree/index_btree.zig");
    _ = @import("btree/balance.zig");
    _ = @import("plan/planner.zig");
    _ = @import("plan/cost.zig");
    _ = @import("plan/optimizer.zig");
    _ = @import("txn/transaction.zig");
    _ = @import("txn/locking.zig");
    _ = @import("version.zig");
}

test "public surface exposes only client concepts" {
    try std.testing.expect(@hasDecl(@This(), "open"));
    try std.testing.expect(@hasDecl(@This(), "Connection"));
    try std.testing.expect(@hasDecl(@This(), "Statement"));
    try std.testing.expect(@hasDecl(@This(), "Result"));
    try std.testing.expect(@hasDecl(@This(), "Value"));
    try std.testing.expect(@hasDecl(@This(), "errors"));
    try std.testing.expect(@hasDecl(@This(), "table"));
    try std.testing.expect(@hasDecl(@This(), "tableWith"));
    try std.testing.expect(@hasDecl(@This(), "DynamicTable"));
    try std.testing.expect(@hasDecl(@This(), "DynamicColumn"));
    try std.testing.expect(@hasDecl(@This(), "SchemaHandle"));
    try std.testing.expect(@hasDecl(@This(), "column"));
    try std.testing.expect(@hasDecl(@This(), "caseWhen"));
    try std.testing.expect(@hasDecl(@This(), "caseValue"));
    try std.testing.expect(@hasDecl(@This(), "rowNumber"));
    try std.testing.expect(@hasDecl(@This(), "rank"));
    try std.testing.expect(@hasDecl(@This(), "denseRank"));
    try std.testing.expect(@hasDecl(@This(), "percentRank"));
    try std.testing.expect(@hasDecl(@This(), "cumeDist"));
    try std.testing.expect(@hasDecl(@This(), "ntile"));
    try std.testing.expect(@hasDecl(@This(), "lag"));
    try std.testing.expect(@hasDecl(@This(), "lead"));
    try std.testing.expect(@hasDecl(@This(), "firstValue"));
    try std.testing.expect(@hasDecl(@This(), "lastValue"));
    try std.testing.expect(@hasDecl(@This(), "nthValue"));
    try std.testing.expect(@hasDecl(@This(), "unboundedPreceding"));
    try std.testing.expect(@hasDecl(@This(), "preceding"));
    try std.testing.expect(@hasDecl(@This(), "currentRow"));
    try std.testing.expect(@hasDecl(@This(), "following"));
    try std.testing.expect(@hasDecl(@This(), "unboundedFollowing"));
    try std.testing.expect(@hasDecl(@This(), "migration"));
    try std.testing.expect(@hasDecl(migration, "Set"));
    try std.testing.expect(@hasDecl(@This(), "version"));
    try std.testing.expect(!@hasDecl(@This(), "format"));
    try std.testing.expect(!@hasDecl(@This(), "storage"));
    try std.testing.expect(!@hasDecl(@This(), "sql"));
    try std.testing.expect(!@hasDecl(@This(), "catalog"));
    try std.testing.expect(!@hasDecl(@This(), "btree"));
    try std.testing.expect(!@hasDecl(@This(), "plan"));
    try std.testing.expect(!@hasDecl(@This(), "vm"));
    try std.testing.expect(!@hasDecl(@This(), "txn"));
    try std.testing.expect(!@hasDecl(@This(), "dsl"));
}
